### ISSUE TITLE
UPX seems to strip some necessary information

### ISSUE THREAD

**Issue by AyrA** [upx/upx#2]
When I compress phantomJS 2.0.0 with any level (1-9) the executable wont run. I can decompress it again, but the result is different from the original file. It has the exact same size but some information at the end is missing and the EXE header seems different too. The decompressed version also doesn't run. I used this version of phantomJS: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-windows.zip

It's over 45 MB and upx would achieve great size (~35% ratio).

**Comment by inexist3nce** [comment]
UPX also breaks the `nw.dll` on NW.js v0.17.1 for Windows. No idea why.

**Comment by AyrA** [comment]
@inexist3nce According to the latest release notes of UPX, it supports 64 bit exe files but this is experimental: https://upx.github.io/upx-news.txt

Maybe we were just unlucky to find exe files that are not yet really supported.

**Comment by Berzeger** [comment]
This might be the same problem - UPX also mangles Qt5WebEngineCore.dll from the Qt Library. It works almost everywhere, but crashes on about 10% of computers (no matter what Windows version).

**Comment by AraHaan** [comment]
I think the problem is that data is at the end of the file and that data is not in a section so that extra data appeneded to it (like a SFX exe for extracting files) is stripped. I know petite made by Ian at un4seen does the same thing. (it also has the same crash for Assemblies that use c99 as UPX has or at least I think the crash is due to c99). For reference the link to Ian's Compressor is http://www.un4seen.com/petite

**Comment by AyrA** [comment]
The weird thing is, that not only is information missing from the end, but the header is also different, which I assume should not happen.

**Comment by ml1050** [comment]
AyrA,

The missing information at the end of your file is the relocation data, which is in theory not strictly necessary for .exe files. You can force UPX to keep that data by using the '--strip-relocs=0' option during compression & decompression. 

UPX works by "rebuilding" the file when you uncompress a compressed executable, which means that the uncompressed file will be not byte identical to the original one (for some executable formats, including PE32/PE64). So this is a feature.

Your file also has TLS callbacks, which may be cause of the crash that you see, as there was a bug in UPX 3.92. I've committed a fix for that on the devel branch. Please try it if you can, and report back the result. I hope it will work, because your file runs fine under wine (I can not do tests under real Windows) even if it is compressed with 3.92.

Others, please also look at my fix on the devel branch.

Thanks.

**Comment by AraHaan** [comment]
you know it would be nice if it would always rename the resource section to ``UPX2`` even if there is no compression to it. (or if there is a little compression to it).

**Comment by ml1050** [comment]
There are reasons why the resource section is handled this way.  The ".rsrc" name was needed because of a windows internal DLL which wanted it. BTW, the resource data is usually not found by looking at the section name, but by using a header field called "data directory". You can the following safely. Just change .rsrc to UPX2, and the resource data will still be found by every utility. Except for that ancient windows internal DLL...

**Comment by AyrA** [comment]
@ml1050 Would it be possible for you to publish a compiled version? I don't have the infrastructure to build UPX

**Comment by ml1050** [comment]
Unfortunately I do not have the windows toolchain installed either. Maybe @markus-oberhumer ?

**Comment by AraHaan** [comment]
@AyrA Cant you manually create a Visual Studio Solution and try to compile with that and under command line options set the asm (s) files to use ``make``?

**Comment by AyrA** [comment]
I would need to install the entire VisualC++ infrastructure for that. Seems
a bit too much considering the fact that the owner can just create a
pre-release with the binaries he just compiled to fix the issue

2016-12-27 23:11 GMT+01:00 AraHaan <notifications@github.com>:

**Comment by ml1050** [comment]
I fixed and tested the issue on linux. I can only build linux binaries.

**Comment by AyrA** [comment]
Then who builds windows binaries?

2016-12-30 17:13 GMT+01:00 László Molnár <notifications@github.com>:

**Comment by ml1050** [comment]
As I wrote earlier:  @markus-oberhumer

**Comment by markus-oberhumer** [comment]
We now have automated builds of the devel branch - please download the current win32 version from

https://github.com/upx/upx-automatic-builds/tree/devel-20170115-120150-ac4b51-travis/i386-w64-mingw32-gcc-4.6-release

**Comment by AyrA** [comment]
I tried this version. It packs the exe file but it still won't run. Windows immediately prints the "Not a valid executable" error. If I decompress the compressed exe file, it has the same size as the original, but a rather large chunk is just zeros. The `-v` command line switch also seems to be doing nothing at the moment.

**Comment by cancerberoSgx** [comment]
https://github.com/zeit/pkg generated executable files are having a problem too that probably is related with this issue. Easy repro steps (in linux but probably reproducible in windows & macos the same way). 

1) install node.js
2) Execute: 
```
$ sudo npm install -g pkg
$ echo "console.log('hello')" > index.js
$ pkg -t node8.6.0-linux index.js -o myexec
$ ./myexec 
hello
$ upx myexec -o myexec2
$ ./myexec2
>
>
```
It seems upx is removing some information and what's happening is that instead of my index.js file being executed, whats is executed is just the node REPL (instead of executing "node index.js" is just executing "node"). I don't know where pkg is storing this meta information but upx is removing it. 

Since upx is safe and in this case is generating a non-equivalent executable I think this is an upx issue, although not 100% sure. 

I tried with other compression levels and options like --strip-relocs=0 --overlay=skip but without luck. 

```
$ upx -V 
upx 3.94
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43
```

Referencing some pkg issues: 
https://github.com/zeit/pkg/issues/121
https://github.com/zeit/pkg/issues/50

**Comment by ssokolow** [comment]
The first thing that'd be important is to figure out where `pkg` is actually storing that information.

(eg. Is it just concatenating it onto the end like a self-extracting archive or actually storing it within the ELF structure the way debugging information is stored?)

**Comment by cancerberoSgx** [comment]
@ssokolow I'm really not sure - I just started using pkg and unfortunately I'm not a binary/ELF - files expert. My bad, maybe this is not a upx issue - but could be related to this one - just wanted to give a heads up. Will try to figure out this info and come back to you, thanks

**Comment by roccomuso** [comment]
@ssokolow it should be storing that information at the end of the file

**Comment by ssokolow** [comment]
If it's just concatenated, then the best solution, if pkg supports it, would be to do what I did with py2exe:

Register a hook which runs "UPX this" code just before the concatenation takes place. (In my py2exe code, the same hook also runs `advzip -z4` on the Zip file that's about to be concatenated on.)

**Comment by phanirithvij** [comment]
I've had this issue with go (golang) binaries on windows but as @ml1050 suggested using `--strip-relocs=0` fixed it

eg: 
```bash
upx out.exe -o comp.exe --strip-relocs=0
upx -d comp.exe -o unpxed.exe --strip-relocs=0
```

###### commenting so anyone who faces this with golang executables can try it out

**Comment by ArkadiuszMichalski** [comment]
For anyone UPX+pkg works even for simple `console.log("hellow world")` on Windows? If yes please share what version Node/UPX/pkg and system you used and what args you used. I always get `Pkg: Error reading from file.`
