### ISSUE TITLE
Rust binary crashes with "Illegal Instruction" on arm64

### ISSUE THREAD

**Issue by ravenclaw900** [upx/upx#534]
## What's the problem (or question)?

When compressing an arm64 rust binary with `--lzma` (dev branch), it crashes with "Illegal Instruction". If I try to compress it with 3.96, I get `CantPackException: bad DT_GNU_HASH n_bucket=0x11  n_bitmask=0x1  len=0x88`

## What should have happened?

Binary compresses and runs fine.

## Do you have an idea for a solution?

No

## How can we reproduce the issue?

1. Try running attached binary

## Please tell us details about your environment.

* UPX version used (`upx --version`):
upx 4.0.0-git-f75ad8ba5c4c
* Host Operating System and version:
Debian 11
* Host CPU architecture:
amd64
* Target Operating System and version:
Raspbian 11
* Target CPU architecture:
arm64
[dietpi-dashboard-armv8.tar.gz](https://github.com/upx/upx/files/7460416/dietpi-dashboard-armv8.tar.gz)

**Comment by wait-what** [comment]
I have the same issue.

- UPX version `upx 3.96-git-d7ba31cab8ce+`
- Host OS `Linux 5.14.15-zen1-1-zen`
- Host architecture: `amd64`
- Target OS Linux `amd64` (`--target=x86_64-unknown-linux-gnu`)
- Target CPU architecture `amd64`

[relay-x86_64-linux.tar.gz](https://github.com/upx/upx/files/7477309/relay-x86_64-linux.tar.gz)

**Comment by jreiser** [comment]
@wait-what  Works for me using tip of `devel` branch:
```
$ ../upx.out -f -o foo relay-x86_64-linux
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-b81491+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   1686472 ->    692232   41.05%   linux/amd64   foo                           

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.

$ ./foo
thread 'main' panicked at 'Couldn't read config.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }', relay/src/main.rs:15:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ export RUST_BACKTRACE=1
$ ./foo
thread 'main' panicked at 'Couldn't read config.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }', relay/src/main.rs:15:62
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

$ export RUST_BACKTRACE=full
$ ./foo
thread 'main' panicked at 'Couldn't read config.json: Os { code: 2, kind: NotFound, message: "No such file or directory" }', relay/src/main.rs:15:62
stack backtrace:
   0:     0x7f799b0523dc - <unknown>
   1:     0x7f799b0031ec - <unknown>
   2:     0x7f799b04c415 - <unknown>
   3:     0x7f799b053950 - <unknown>
   4:     0x7f799b05415f - <unknown>
   5:     0x7f799b053a9a - <unknown>
   6:     0x7f799b052ae4 - <unknown>
   7:     0x7f799b053a1d - <unknown>
   8:     0x7f799afc4b31 - <unknown>
   9:     0x7f799afc4c23 - <unknown>
  10:     0x7f799b02209d - <unknown>
  11:     0x7f799b028e13 - <unknown>
  12:     0x7f799b01c669 - <unknown>
  13:     0x7f799b051b97 - <unknown>
  14:     0x7f799b022a52 - <unknown>
  15:     0x7f799aa45b75 - __libc_start_main
  16:     0x7f799afc953e - <unknown>
  17:                0x0 - <unknown>
```
See https://github.com/upx/upx-automatic-builds then https://github.com/upx/upx/actions for recent builds.

**Comment by mprimeaux** [comment]
Given 3.96 was released nearly 22 months ago, when do you expect a new release to be created with this fix?

**Comment by wait-what** [comment]
It's the one in [Arch repos](https://archlinux.org/packages/community/x86_64/upx/), so I assumed it was recent. Sorry for wasting your time, I'll use the latest one from AUR

**Comment by xyproto** [comment]
Please consider clicking the "Flag Package Out-of-Date" link at the Arch Linux package page for UPX if the package is out of date:

https://archlinux.org/packages/community/x86_64/upx/

**Comment by xyproto** [comment]
Arch Linux maintainer of the `upx` package here. I would love to update it, when there is a new release. I might apply patches in the mean time.

I also get errors when using UPX on executables compiled with Go. Attaching a gzipped ELF.

[getdpi.gz](https://github.com/upx/upx/files/7528636/getdpi.gz)

**Comment by jreiser** [comment]
@xyproto  Tip of `devel` branch works for me on `getdpi`:
```
$ ./upx.out -f -o foo getdpi
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-63fba2+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   4242368 ->   1532392   36.12%   linux/amd64   foo                           

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
$ gdb ./foo
(gdb) run
Starting program: /bigdata/home2/upx/src/github-issue534/foo 
[New LWP 199920]
[New LWP 199921]
[New LWP 199922]
[New LWP 199923]
[New LWP 199924]
[New LWP 199925]
108
[LWP 199925 exited]
[LWP 199924 exited]
[LWP 199922 exited]
[LWP 199921 exited]
[LWP 199920 exited]
[LWP 199916 exited]
[Inferior 1 (process 199916) exited normally]
```

**Comment by sonicrules1234** [comment]
I'm having the illegal instruction issue with aarch64 when built with musl.
[aarch64-upx-test-musl.zip](https://github.com/upx/upx/files/8319887/aarch64-upx-test-musl.zip)

**Comment by markus-oberhumer** [comment]
Is this fixed in current git?

**Comment by Hypfer** [comment]
Using the CI amd64-win64-msvc-14.2 build for [bca5ea1](https://github.com/upx/upx/commit/bca5ea1cdc2ecff9f4edead445c4faf8aab93644) from https://github.com/upx/upx/actions/runs/2853141657, unfortunately, I still get `Illegal instruction (core dumped)` when attempting to run an LZMA UPX compressed arm64 linux binary.

The attached zip contains both the uncompressed and compressed version of the binary I've used to test this
[valetudo_upx_arm64_lzma_example.zip](https://github.com/upx/upx/files/9365785/valetudo_upx_arm64_lzma_example.zip)

**Comment by xyproto** [comment]
`upx` has worked great for executables produced by the Go compiler for some time now, so at least that is no longer an issue (ref. my comment a bit further up).

**Comment by mprimeaux** [comment]
@xyproto As a related question, I install via `brew install upx` on macOS intel. I also have macOS arm64, which doesn't seem to have a related brew formula. 

I noticed the the [releases](https://github.com/upx/upx/releases) page does not mention macOS. Appreciate your thoughts.

**Comment by xyproto** [comment]
@mprimeaux  I only maintain the upx package for Arch Linux, so I'm not quite sure.

**Comment by mprimeaux** [comment]
Thank, @xyproto. Appreciate the response.

**Comment by jreiser** [comment]
@Hypfer  valetudo fixed on `devel` branch by commit above.
